{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "auth_users_active_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_attempts_success_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_attempts_failure_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "HTTP Requests/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_post_count_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(http_requests_get_count_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(http_requests_delete_count_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(http_requests_put_count_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(http_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "CPU/Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "system_cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_requests_latency_sum_milliseconds_total{source=\"jwt-pizza-service\"}[1m]) / (rate(http_requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Purchased",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(order_pizzas_sold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PizzaSold/Minute"
    },
    {
     "expr": "order_pizza_creation_failures_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Failed Orders"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(order_revenue_cents_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue/Minute"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "rate(order_pizza_creation_latency_sum_milliseconds_total{source=\"jwt-pizza-service\"}[1m]) / (rate(order_pizza_creation_count_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Pizza Latency"
    }
   ]
  }
 ]
}